package generator

import (
	"fmt"
	"math"
	"math/rand"
	"sort"

	"beats-bitwrap-io/internal/pflow"

	"github.com/pflow-xyz/go-pflow/petri"
)

// boundaryStagger spreads simultaneous unmute / activate-slot firings at
// section / phrase boundaries across a window of ticks. Without this,
// every role's struct-* control net activates its next slot on the
// exact same tick — a "blast" re-entry. 12 ticks ≈ 3 beats at PPQ=4:
// enough slots to fully separate the typical 10–12 roles + stinger
// targets in an arrangement (drum slots, bass, harmony variants, hits),
// while keeping every role inside the same bar as the boundary.
// mute-track firings are NOT staggered (silence has no transient).
const boundaryStagger = 12

// Section defines a segment of a song structure.
type Section struct {
	Name    string
	Steps   int
	Active  map[string]bool     // net IDs that should be audible
	Phrases map[string][]string // role -> phrase variant sequence, e.g. {"kick": ["A","A","B","A"]}
}

// DefaultPhrases returns phrase patterns for a given section type.
func DefaultPhrases(sectionName string) []string {
	switch sectionName {
	case "intro", "outro":
		return []string{"A", "A"}
	case "verse":
		return []string{"A", "A", "B", "A"}
	case "chorus", "drop":
		return []string{"A", "B", "A", "B"}
	case "bridge", "breakdown":
		return []string{"C", "C"}
	case "buildup", "pre-chorus":
		return []string{"A", "B"}
	case "solo":
		return []string{"A", "B", "C", "A"}
	default:
		return []string{"A", "A"}
	}
}

// SongTemplate defines a sequence of sections.
type SongTemplate struct {
	Name     string
	Sections []Section
	// SlotMap is populated by expandVariants: role -> [sectionIdx][phraseIdx] -> global slot index.
	// -1 means the role is inactive in that phrase slot.
	SlotMap map[string][][]int
}

// Track roles used in templates. These map to the music net IDs
// generated by Compose (kick, snare, hihat, bass, melody, harmony, arp, clap).
var drumRoles = map[string]bool{"kick": true, "snare": true, "hihat": true, "clap": true}

// noVariantRoles are roles that should not get phrase variants — they just
// play a single looping pattern and get muted/unmuted per section.
var noVariantRoles = map[string]bool{"snare": true}

// sectionWithPhrases creates a Section with default phrase patterns for all active roles.
func sectionWithPhrases(name string, steps int, active map[string]bool) Section {
	phrases := make(map[string][]string)
	pattern := DefaultPhrases(name)
	for role := range active {
		if noVariantRoles[role] {
			continue
		}
		phrases[role] = pattern
	}
	return Section{Name: name, Steps: steps, Active: active, Phrases: phrases}
}

// sectionArchetypes defines the default active roles for each section
// type. Per-family overrides live in sectionArchetypesByFamily — use
// archetypeFor(family, name) to resolve them.
var sectionArchetypes = map[string]map[string]bool{
	"intro":      {"kick": true, "hihat": true, "bass": true},
	"verse":      {"kick": true, "snare": true, "hihat": true, "bass": true},
	"pre-chorus": {"kick": true, "snare": true, "hihat": true, "bass": true, "arp": true},
	"chorus":     {"kick": true, "snare": true, "hihat": true, "bass": true, "melody": true, "harmony": true, "arp": true, "clap": true},
	"drop":       {"kick": true, "snare": true, "hihat": true, "bass": true, "melody": true, "harmony": true, "arp": true, "clap": true},
	"buildup":    {"kick": true, "snare": true, "hihat": true, "bass": true, "arp": true},
	"breakdown":  {"hihat": true, "bass": true, "melody": true},
	"bridge":     {"bass": true, "melody": true, "harmony": true},
	"solo":       {"kick": true, "hihat": true, "bass": true, "melody": true},
	"outro":      {"kick": true, "hihat": true, "melody": true},
}

// sectionArchetypesByFamily holds sparse per-family overrides for the
// default archetype map above. A family that doesn't override a section
// inherits the default. Used to make jazz "verse" actually sound like
// jazz (no four-on-the-floor) and ambient "chorus" actually sound like
// ambient (no kick/snare/clap).
var sectionArchetypesByFamily = map[structureFamily]map[string]map[string]bool{
	familyEDM: {
		// EDM intros are typically rhythm-only; bass arrives later
		// with the buildup. Breakdowns drop the melodic layer to
		// leave just the rhythmic skeleton + low end.
		"intro":     {"kick": true, "hihat": true},
		"breakdown": {"hihat": true, "bass": true},
	},
	familySong: {
		// Pre-chorus drops hihat to build tension (the cymbal lifts
		// when the chorus kicks back in). Outro keeps bass for shape.
		"pre-chorus": {"kick": true, "snare": true, "bass": true, "arp": true},
		"outro":      {"kick": true, "hihat": true, "bass": true, "melody": true},
	},
	familyJazz: {
		// Jazz drops the four-on-floor kick + backbeat snare in
		// favour of ride-cymbal (hihat) + walking bass + melody.
		"intro":  {"hihat": true, "bass": true},
		"verse":  {"hihat": true, "bass": true, "melody": true},
		"chorus": {"hihat": true, "bass": true, "melody": true, "harmony": true},
		"solo":   {"hihat": true, "bass": true, "melody": true},
	},
	familyChill: {
		// Ambient/lofi: minimize percussion. Intro is pad-only,
		// breakdowns / outros fade to a single melodic layer.
		"intro":      {"bass": true},
		"verse":      {"hihat": true, "bass": true, "melody": true},
		"chorus":     {"hihat": true, "bass": true, "melody": true, "harmony": true, "arp": true},
		"bridge":     {"bass": true, "melody": true},
		"breakdown":  {"melody": true},
		"outro":      {"melody": true},
	},
}

// archetypeFor resolves the active-role set for a section, applying any
// family-specific override over the default archetype map.
func archetypeFor(family structureFamily, sectionName string) map[string]bool {
	if overrides, ok := sectionArchetypesByFamily[family]; ok {
		if a, ok := overrides[sectionName]; ok {
			return a
		}
	}
	return sectionArchetypes[sectionName]
}

// sectionStep returns the step count for a section at a given template size.
func sectionSteps(name, size string) int {
	switch size {
	case "minimal":
		switch name {
		case "intro", "outro":
			return 32
		default:
			return 128
		}
	case "extended":
		switch name {
		case "intro", "outro", "breakdown", "bridge", "buildup", "pre-chorus", "solo":
			return 128
		default:
			return 192
		}
	default: // standard
		switch name {
		case "intro", "outro", "breakdown", "bridge", "pre-chorus", "solo":
			return 64
		default:
			return 192
		}
	}
}

// genreStructureFamily groups genres by their preferred structure style.
type structureFamily int

const (
	familyEDM   structureFamily = iota // buildup/drop oriented
	familySong                         // verse/chorus oriented
	familyJazz                         // head/solo oriented
	familyChill                        // ambient/minimal sections
)

var genreFamilies = map[string]structureFamily{
	"techno":    familyEDM,
	"house":     familyEDM,
	"edm":       familyEDM,
	"trance":    familyEDM,
	"dnb":       familyEDM,
	"dubstep":   familyEDM,
	"speedcore": familyEDM,
	"garage":    familyEDM,
	"trap":      familyEDM,
	"country":   familySong,
	"blues":     familySong,
	"funk":      familySong,
	"reggae":    familySong,
	"synthwave": familySong,
	"metal":     familySong,
	"jazz":      familyJazz,
	"bossa":     familyJazz,
	"ambient":   familyChill,
	"lofi":      familyChill,
	// "wrapped" is the hand-authored share tag. Default it to EDM-family
	// blueprints (buildup/drop/breakdown) since authored tracks typically
	// skew that direction; authors can always pass an explicit genre hint
	// to /api/arrange if they want verse/chorus or jazz-style structures.
	"wrapped":   familyEDM,
}

// structureBlueprints defines possible section sequences per family and size.
// Each blueprint is a list of section names that get expanded with sectionArchetypes.
var structureBlueprints = map[structureFamily]map[string][][]string{
	familyEDM: {
		"minimal": {
			{"intro", "buildup", "drop", "outro"},
			{"intro", "drop", "breakdown", "drop"},
		},
		"standard": {
			{"intro", "buildup", "drop", "breakdown", "buildup", "drop", "outro"},
			{"intro", "verse", "buildup", "drop", "breakdown", "drop", "outro"},
			{"intro", "buildup", "drop", "verse", "drop", "outro"},
		},
		"extended": {
			{"intro", "buildup", "drop", "breakdown", "verse", "buildup", "drop", "bridge", "chorus", "outro"},
			{"intro", "verse", "buildup", "drop", "breakdown", "buildup", "drop", "chorus", "outro"},
			{"intro", "buildup", "drop", "verse", "breakdown", "buildup", "drop", "bridge", "drop", "outro"},
			{"intro", "verse", "pre-chorus", "drop", "breakdown", "verse", "buildup", "drop", "outro"},
		},
		"ab": {
			{"verse", "drop", "verse", "drop"},
			{"buildup", "drop", "buildup", "drop"},
			{"verse", "chorus", "verse", "chorus"},
		},
		"drop": {
			{"drop", "breakdown", "drop", "breakdown", "drop"},
			{"buildup", "drop", "breakdown", "drop"},
			{"drop", "verse", "drop", "verse", "drop"},
		},
		"build": {
			{"buildup", "drop", "buildup", "drop", "buildup", "drop"},
			{"verse", "buildup", "drop", "buildup", "drop"},
		},
		"jam": {
			{"verse", "solo", "verse", "solo", "verse"},
			{"verse", "bridge", "verse", "solo", "verse"},
			{"drop", "solo", "drop", "bridge", "drop"},
		},
	},
	familySong: {
		"minimal": {
			{"intro", "verse", "chorus", "outro"},
			{"intro", "verse", "verse", "chorus"},
		},
		"standard": {
			{"intro", "verse", "chorus", "verse", "chorus", "outro"},
			{"intro", "verse", "chorus", "bridge", "chorus", "outro"},
			{"intro", "verse", "pre-chorus", "chorus", "verse", "chorus", "outro"},
		},
		"extended": {
			{"intro", "verse", "chorus", "verse", "chorus", "bridge", "chorus", "outro"},
			{"intro", "verse", "pre-chorus", "chorus", "verse", "pre-chorus", "chorus", "bridge", "chorus", "outro"},
			{"intro", "verse", "chorus", "verse", "chorus", "breakdown", "verse", "chorus", "outro"},
			{"intro", "verse", "verse", "chorus", "bridge", "verse", "chorus", "chorus", "outro"},
		},
		"ab": {
			{"verse", "chorus", "verse", "chorus"},
			{"verse", "chorus", "bridge", "chorus"},
			{"verse", "pre-chorus", "chorus", "verse", "chorus"},
		},
		"drop": {
			{"chorus", "verse", "chorus", "verse", "chorus"},
			{"chorus", "bridge", "chorus", "bridge", "chorus"},
		},
		"build": {
			{"verse", "pre-chorus", "chorus", "verse", "pre-chorus", "chorus"},
			{"verse", "buildup", "chorus", "verse", "buildup", "chorus"},
		},
		"jam": {
			{"verse", "solo", "verse", "solo", "verse"},
			{"verse", "bridge", "solo", "verse", "solo"},
			{"verse", "verse", "bridge", "solo", "verse"},
		},
	},
	familyJazz: {
		"minimal": {
			{"intro", "verse", "solo", "outro"},
			{"intro", "verse", "verse", "outro"},
		},
		"standard": {
			{"intro", "verse", "solo", "verse", "outro"},
			{"intro", "verse", "verse", "bridge", "verse", "outro"},
			{"intro", "verse", "chorus", "solo", "chorus", "outro"},
		},
		"extended": {
			{"intro", "verse", "chorus", "solo", "verse", "chorus", "bridge", "chorus", "outro"},
			{"intro", "verse", "solo", "verse", "bridge", "solo", "verse", "outro"},
			{"intro", "verse", "verse", "solo", "bridge", "verse", "chorus", "outro"},
		},
		"ab": {
			{"verse", "solo", "verse", "solo"},
			{"verse", "bridge", "verse", "solo"},
		},
		"drop": {
			{"verse", "solo", "verse", "solo", "verse"},
			{"solo", "verse", "bridge", "solo", "verse"},
		},
		"build": {
			{"verse", "verse", "solo", "verse", "solo", "solo"},
		},
		"jam": {
			{"verse", "solo", "solo", "bridge", "solo", "verse"},
			{"solo", "bridge", "solo", "verse", "solo"},
			{"verse", "solo", "verse", "bridge", "solo", "solo"},
		},
	},
	familyChill: {
		"minimal": {
			{"intro", "verse", "verse", "outro"},
			{"intro", "verse", "bridge", "outro"},
		},
		"standard": {
			{"intro", "verse", "bridge", "verse", "outro"},
			{"intro", "verse", "breakdown", "verse", "outro"},
			{"intro", "verse", "verse", "bridge", "verse", "outro"},
		},
		"extended": {
			{"intro", "verse", "chorus", "breakdown", "verse", "chorus", "outro"},
			{"intro", "verse", "bridge", "verse", "breakdown", "verse", "bridge", "outro"},
			{"intro", "verse", "verse", "bridge", "breakdown", "verse", "chorus", "outro"},
		},
		"ab": {
			{"verse", "bridge", "verse", "bridge"},
			{"verse", "breakdown", "verse", "bridge"},
		},
		"drop": {
			{"verse", "breakdown", "verse", "breakdown", "verse"},
			{"verse", "bridge", "breakdown", "verse", "bridge"},
		},
		"build": {
			{"verse", "verse", "bridge", "verse", "chorus"},
			{"breakdown", "verse", "bridge", "verse", "chorus"},
		},
		"jam": {
			{"verse", "bridge", "verse", "breakdown", "verse"},
			{"verse", "verse", "bridge", "breakdown", "verse", "bridge"},
		},
	},
}

// GenerateStructure creates a randomized SongTemplate appropriate for the genre.
func GenerateStructure(genreName, size string, rng *rand.Rand) *SongTemplate {
	family := genreFamilies[genreName]
	blueprints, ok := structureBlueprints[family][size]
	if !ok {
		blueprints = structureBlueprints[familySong]["standard"]
	}

	blueprint := blueprints[rng.Intn(len(blueprints))]

	sections := make([]Section, len(blueprint))
	for i, name := range blueprint {
		active := make(map[string]bool)
		for k, v := range archetypeFor(family, name) {
			active[k] = v
		}
		steps := sectionSteps(name, size)
		sections[i] = sectionWithPhrases(name, steps, active)
	}

	return &SongTemplate{
		Name:     size,
		Sections: sections,
	}
}

// SongTemplates contains fallback preset song structures (used by tests).
var SongTemplates = map[string]*SongTemplate{
	"standard": {
		Name: "standard",
		Sections: []Section{
			sectionWithPhrases("intro", 64, sectionArchetypes["intro"]),
			sectionWithPhrases("verse", 192, sectionArchetypes["verse"]),
			sectionWithPhrases("chorus", 192, sectionArchetypes["chorus"]),
			sectionWithPhrases("breakdown", 64, sectionArchetypes["breakdown"]),
			sectionWithPhrases("verse", 192, sectionArchetypes["verse"]),
			sectionWithPhrases("chorus", 192, sectionArchetypes["chorus"]),
			sectionWithPhrases("outro", 64, sectionArchetypes["outro"]),
		},
	},
	"minimal": {
		Name: "minimal",
		Sections: []Section{
			sectionWithPhrases("intro", 32, sectionArchetypes["intro"]),
			sectionWithPhrases("verse", 128, sectionArchetypes["verse"]),
			sectionWithPhrases("chorus", 128, sectionArchetypes["chorus"]),
			sectionWithPhrases("outro", 32, sectionArchetypes["outro"]),
		},
	},
	"extended": {
		Name: "extended",
		Sections: []Section{
			sectionWithPhrases("intro", 128, sectionArchetypes["intro"]),
			sectionWithPhrases("buildup", 128, sectionArchetypes["buildup"]),
			sectionWithPhrases("drop", 192, sectionArchetypes["drop"]),
			sectionWithPhrases("breakdown", 128, sectionArchetypes["breakdown"]),
			sectionWithPhrases("verse", 192, sectionArchetypes["verse"]),
			sectionWithPhrases("buildup", 128, sectionArchetypes["buildup"]),
			sectionWithPhrases("drop", 192, sectionArchetypes["drop"]),
			sectionWithPhrases("bridge", 128, sectionArchetypes["bridge"]),
			sectionWithPhrases("chorus", 192, sectionArchetypes["chorus"]),
			sectionWithPhrases("outro", 128, sectionArchetypes["outro"]),
		},
	},
}

// SongStructure builds linear control nets that implement a song structure.
// For roles with slot variants, it creates one control net per role that
// uses activate-slot to switch between slot nets at phrase boundaries.
// A stop net fires stop-transport at the end.
// Returns the list of net IDs that should start muted.
func SongStructure(proj *pflow.Project, template *SongTemplate, musicNets []string) []string {
	totalSteps := 0
	for _, sec := range template.Sections {
		totalSteps += sec.Steps
	}

	var initialMutes []string

	// Build set of base roles that have slot variants
	slotRoles := make(map[string]bool)
	for _, netId := range musicNets {
		if nb, ok := proj.Nets[netId]; ok && nb.RiffGroup != "" {
			slotRoles[nb.RiffGroup] = true
		}
	}

	// Build a deterministic stagger offset per control-net target so unmute /
	// activate-slot events at the same boundary land on different ticks.
	var staggerKeys []string
	seenForStagger := make(map[string]bool)
	for _, netId := range musicNets {
		nb, ok := proj.Nets[netId]
		if !ok {
			continue
		}
		key := netId
		if nb.RiffGroup != "" {
			key = nb.RiffGroup
		} else if slotRoles[netId] {
			continue
		}
		if seenForStagger[key] {
			continue
		}
		seenForStagger[key] = true
		staggerKeys = append(staggerKeys, key)
	}
	sort.Strings(staggerKeys)
	staggerOf := make(map[string]int, len(staggerKeys))
	for i, k := range staggerKeys {
		staggerOf[k] = i % boundaryStagger
	}

	// Build one control net per role (using SlotMap)
	processedRoles := make(map[string]bool)
	for _, netId := range musicNets {
		nb, ok := proj.Nets[netId]
		if !ok {
			continue
		}

		if nb.RiffGroup != "" {
			role := nb.RiffGroup
			if processedRoles[role] {
				continue
			}
			processedRoles[role] = true

			slotMap := template.SlotMap[role]
			ctrl := roleControlNet(role, slotMap, template, totalSteps, staggerOf[role])
			proj.Nets[fmt.Sprintf("struct-%s", role)] = ctrl

			// Determine initial mutes: all slot nets start muted except the first active one
			firstSlot := -1
			if len(slotMap) > 0 && len(slotMap[0]) > 0 {
				firstSlot = slotMap[0][0]
			}
			for _, nId := range musicNets {
				if nb2, ok := proj.Nets[nId]; ok && nb2.RiffGroup == role {
					slotIdx := ExtractSlotIndex(nId, role)
					if slotIdx != firstSlot || firstSlot < 0 {
						initialMutes = append(initialMutes, nId)
					}
				}
			}
		} else if !slotRoles[netId] {
			// Stingers are one-shot accents and must never be driven by
			// section structure — skip the control net entirely and
			// keep them muted from the start.
			if pflow.IsStingerNet(netId, nb) {
				initialMutes = append(initialMutes, netId)
				continue
			}
			// Non-variant net — use original section-boundary control
			ctrl := linearControlNet(netId, template, totalSteps, staggerOf[netId])
			proj.Nets[fmt.Sprintf("struct-%s", netId)] = ctrl

			if !template.Sections[0].Active[netId] {
				initialMutes = append(initialMutes, netId)
			}
		}
	}

	// Stop net
	proj.Nets["struct-stop"] = linearStopNet(totalSteps)

	// Store structure metadata for timeline display
	sections := make([]pflow.StructureSection, len(template.Sections))
	for i, sec := range template.Sections {
		ss := pflow.StructureSection{Name: sec.Name, Steps: sec.Steps}
		if sec.Phrases != nil {
			ss.Phrases = make(map[string][]string)
			for role, phrases := range sec.Phrases {
				ss.Phrases[role] = phrases
			}
		}
		sections[i] = ss
	}
	proj.Structure = sections

	return initialMutes
}

// ExtractSlotIndex parses a slot index from a net ID like "kick-3" -> 3.
func ExtractSlotIndex(netId, riffGroup string) int {
	suffix := netId[len(riffGroup)+1:]
	idx := 0
	for _, c := range suffix {
		if c >= '0' && c <= '9' {
			idx = idx*10 + int(c-'0')
		}
	}
	return idx
}

// roleControlNet creates a single linear control net for a role.
// It uses activate-slot at phrase boundaries to switch between slot nets,
// and mute-track when the role becomes inactive in a section.
func roleControlNet(role string, slotMap [][]int, template *SongTemplate, totalSteps, stagger int) *pflow.NetBundle {
	net := petri.NewPetriNet()
	controlBindings := make(map[string]*pflow.ControlBinding)

	cx, cy, radius := ringLayout(totalSteps)

	// Build the schedule of active slots at each phrase boundary
	prevSlot := -1
	if len(slotMap) > 0 && len(slotMap[0]) > 0 {
		prevSlot = slotMap[0][0]
	}

	pos := 0
	for si, sec := range template.Sections {
		phrases := sec.Phrases[role]
		if len(phrases) == 0 {
			phrases = []string{"A"}
		}
		phraseLen := sec.Steps / len(phrases)

		for pi := range phrases {
			phraseStart := pos + pi*phraseLen
			if phraseStart == 0 {
				continue // initial state handled by initialMutes
			}

			curSlot := -1
			if si < len(slotMap) && pi < len(slotMap[si]) {
				curSlot = slotMap[si][pi]
			}

			if curSlot != prevSlot {
				// Stagger the activate-slot — but never the mute, and never
				// past the next phrase or the end of the chain.
				bindPos := phraseStart
				if curSlot >= 0 && stagger > 0 {
					maxOff := totalSteps - 1 - phraseStart
					if maxOff > phraseLen-1 {
						maxOff = phraseLen - 1
					}
					off := stagger
					if off > maxOff {
						off = maxOff
					}
					if off < 0 {
						off = 0
					}
					bindPos = phraseStart + off
				}
				tLabel := fmt.Sprintf("t%d", bindPos)
				if curSlot >= 0 {
					// Activate new slot (mutes all others in riff group, unmutes target)
					controlBindings[tLabel] = &pflow.ControlBinding{
						Action:    "activate-slot",
						TargetNet: fmt.Sprintf("%s-%d", role, curSlot),
					}
				} else {
					// Role becomes inactive — mute the outgoing slot
					controlBindings[tLabel] = &pflow.ControlBinding{
						Action:    "mute-track",
						TargetNet: fmt.Sprintf("%s-%d", role, prevSlot),
					}
				}
				prevSlot = curSlot
			}
		}
		pos += sec.Steps
	}

	// Build linear chain: totalSteps places + sink, totalSteps transitions
	for i := 0; i < totalSteps; i++ {
		initial := 0.0
		if i == 0 {
			initial = 1
		}
		angle := float64(i) / float64(totalSteps) * 2 * math.Pi
		x := cx + radius*0.7*math.Cos(angle)
		y := cy + radius*0.7*math.Sin(angle)
		net.AddPlace(fmt.Sprintf("p%d", i), initial, nil, x, y, nil)
	}

	// Sink place
	sinkAngle := float64(totalSteps) / float64(totalSteps) * 2 * math.Pi
	sinkX := cx + radius*0.7*math.Cos(sinkAngle)
	sinkY := cx + radius*0.7*math.Sin(sinkAngle)
	net.AddPlace(fmt.Sprintf("p%d", totalSteps), 0, nil, sinkX, sinkY, nil)

	for i := 0; i < totalSteps; i++ {
		tLabel := fmt.Sprintf("t%d", i)
		angle := (float64(i) + 0.5) / float64(totalSteps) * 2 * math.Pi
		tx := cx + radius*math.Cos(angle)
		ty := cy + radius*math.Sin(angle)
		net.AddTransition(tLabel, "", tx, ty, nil)

		net.AddArc(fmt.Sprintf("p%d", i), tLabel, 1.0, false)
		net.AddArc(tLabel, fmt.Sprintf("p%d", i+1), 1.0, false)
	}

	track := pflow.Track{Channel: 1}
	nb := pflow.NewNetBundle(net, track, make(map[string]*pflow.MidiBinding))
	nb.Role = "control"
	nb.ControlBindings = controlBindings
	return nb
}

// linearControlNet creates a linear chain of places (not a ring).
// At section boundaries where the target net's active state changes,
// it emits mute-track or unmute-track control bindings.
func linearControlNet(targetNet string, template *SongTemplate, totalSteps, stagger int) *pflow.NetBundle {
	net := petri.NewPetriNet()
	controlBindings := make(map[string]*pflow.ControlBinding)

	cx, cy, radius := ringLayout(totalSteps)

	// Linear chain: totalSteps places, totalSteps-1 transitions
	// (last place is a sink — token stays there)
	for i := 0; i < totalSteps; i++ {
		initial := 0.0
		if i == 0 {
			initial = 1
		}
		angle := float64(i) / float64(totalSteps) * 2 * math.Pi
		x := cx + radius*0.7*math.Cos(angle)
		y := cy + radius*0.7*math.Sin(angle)
		pLabel := fmt.Sprintf("p%d", i)
		net.AddPlace(pLabel, initial, nil, x, y, nil)
	}

	// Add sink place at end
	sinkAngle := float64(totalSteps) / float64(totalSteps) * 2 * math.Pi
	sinkX := cx + radius*0.7*math.Cos(sinkAngle)
	sinkY := cx + radius*0.7*math.Sin(sinkAngle)
	net.AddPlace(fmt.Sprintf("p%d", totalSteps), 0, nil, sinkX, sinkY, nil)

	// Build section boundary positions
	wasActive := template.Sections[0].Active[targetNet]
	pos := 0
	for si := 1; si < len(template.Sections); si++ {
		pos += template.Sections[si-1].Steps
		isActive := template.Sections[si].Active[targetNet]
		if isActive != wasActive {
			// Stagger only the unmute side, and never past the next section.
			bindPos := pos
			if isActive && stagger > 0 {
				nextSec := totalSteps
				if si+1 < len(template.Sections) {
					nextSec = pos + template.Sections[si].Steps
				}
				maxOff := nextSec - pos - 1
				off := stagger
				if off > maxOff {
					off = maxOff
				}
				if off < 0 {
					off = 0
				}
				bindPos = pos + off
			}
			tLabel := fmt.Sprintf("t%d", bindPos)
			if isActive {
				controlBindings[tLabel] = &pflow.ControlBinding{
					Action:    "unmute-track",
					TargetNet: targetNet,
				}
			} else {
				controlBindings[tLabel] = &pflow.ControlBinding{
					Action:    "mute-track",
					TargetNet: targetNet,
				}
			}
			wasActive = isActive
		}
	}

	// Transitions: one per step, connecting p[i] -> p[i+1]
	for i := 0; i < totalSteps; i++ {
		tLabel := fmt.Sprintf("t%d", i)
		angle := (float64(i) + 0.5) / float64(totalSteps) * 2 * math.Pi
		tx := cx + radius*math.Cos(angle)
		ty := cy + radius*math.Sin(angle)
		net.AddTransition(tLabel, "", tx, ty, nil)

		net.AddArc(fmt.Sprintf("p%d", i), tLabel, 1.0, false)
		net.AddArc(tLabel, fmt.Sprintf("p%d", i+1), 1.0, false)
	}

	track := pflow.Track{Channel: 1}
	nb := pflow.NewNetBundle(net, track, make(map[string]*pflow.MidiBinding))
	nb.Role = "control"
	nb.ControlBindings = controlBindings
	return nb
}

// linearStopNet creates a linear chain where the final transition
// fires a stop-transport control binding.
func linearStopNet(totalSteps int) *pflow.NetBundle {
	net := petri.NewPetriNet()
	controlBindings := make(map[string]*pflow.ControlBinding)

	cx, cy, radius := ringLayout(totalSteps + 1)

	// totalSteps+1 places, totalSteps transitions
	for i := 0; i <= totalSteps; i++ {
		initial := 0.0
		if i == 0 {
			initial = 1
		}
		angle := float64(i) / float64(totalSteps+1) * 2 * math.Pi
		x := cx + radius*0.7*math.Cos(angle)
		y := cy + radius*0.7*math.Sin(angle)
		pLabel := fmt.Sprintf("p%d", i)
		net.AddPlace(pLabel, initial, nil, x, y, nil)
	}

	for i := 0; i < totalSteps; i++ {
		tLabel := fmt.Sprintf("t%d", i)
		angle := (float64(i) + 0.5) / float64(totalSteps+1) * 2 * math.Pi
		tx := cx + radius*math.Cos(angle)
		ty := cy + radius*math.Sin(angle)
		net.AddTransition(tLabel, "", tx, ty, nil)

		net.AddArc(fmt.Sprintf("p%d", i), tLabel, 1.0, false)
		net.AddArc(tLabel, fmt.Sprintf("p%d", i+1), 1.0, false)

		// Last transition fires stop-transport
		if i == totalSteps-1 {
			controlBindings[tLabel] = &pflow.ControlBinding{
				Action: "stop-transport",
			}
		}
	}

	track := pflow.Track{Channel: 1}
	nb := pflow.NewNetBundle(net, track, make(map[string]*pflow.MidiBinding))
	nb.Role = "control"
	nb.ControlBindings = controlBindings
	return nb
}
